### ISSUE TITLE
Documentation Link Broken

### ISSUE THREAD

**Issue by rawrmonstar** [JoviDeCroock/Hooked-Form#103]
Hello! The documentation link at the top of the repo and inside the readme do not work for me:

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/13814048/76704504-a5bd5e00-6696-11ea-8d7f-33cdb5f6bb26.png">

The capitalization of `Hooked-Form` is what seems like is the cause: https://jovidecroock.github.io/Hooked-Form does reach some HTML (but without any CSS and none of the links working due to the same capitalization issue).

**Comment by JoviDeCroock** [comment]
Hey,

Thanks for the issue, everything should be fixed now, I changed the capitalization not that long ago and seems like I forgot to publish the website! Thank you so much for bringing this to my ears, my goal is to have better documentation in the near future so any feedback will be welcome!

**Comment by rawrmonstar** [comment]
Thanks! it's all working for me now 🙇‍♀️

**Comment by JoviDeCroock** [comment]
@@all-contributors please add tatchi for bug

**Comment by JoviDeCroock** [comment]
@all-contributors please add rawrmonstar for bug
