### ISSUE TITLE
[question] using `useFieldArray` for flat array of strings?

### ISSUE THREAD

**Issue by stefanprobst** [JoviDeCroock/Hooked-Form#130]
hi, what is the recommended way to use `useFieldArray` for a flat array of strings, i.e. not `{ friends: [{ name: 'one' }, { name: 'two' }] }` but `{ friends: ['one', 'two'] }`?

from what i understand from the docs, `useFieldArray`requires an array of objects with an `id` property (which is also what `react-hook-form` and i believe `formik` do as well), but it is unclear to me how then to use `useFieldArray` with flat arrays? thanks!

**Comment by JoviDeCroock** [comment]
Should just work https://codesandbox.io/s/hooked-form-forked-ix8gb?file=/src/index.js

**Comment by stefanprobst** [comment]
great, thanks!
