### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by lishine** [JoviDeCroock/Hooked-Form#95]
First meeting your lib and I am impressed.
I have built this form lib after using formik and trying react-hook-form (the hyped lib).
https://github.com/lishine/mobx-hooks-form
It is built with mobx.
If running my codesandbox, it can be seen that there are zero useless re-renders.
And I see that you put this target as well...
I was looking to do same result but without mobx, so was thinking about emitter pattern and useField, and stumbled across your lib, great!

After a first glance at your lib (I will play with it later on probably)
What I would like to see (just trying to find common understanding):

1. yup validation
2. performance comparison to react-hook-form
3. validateOnBlur as default
4. id generator - between label and input field

I have used tsdx, you used microbundle, how did you decide that ?

**Comment by JoviDeCroock** [comment]
Hey,

First and foremost welcome, so the goal of this lib is to be minimalistic (2kb) and performant, this means that things like yup validation and so on are left to the user. You can use the `validate` property however you like.
Performance of `hooked-form` is just a tad slower than `final-form` currently the fastest form-library (behind uncontrolled input ofcourse). `validateOnBlur` can become the default, it used to be before.
an id-generator can just be done with the fieldId in 99% of the cases so which also ties in to minimalistic.

Microbundle is focussed on providing the smallest bundle possible for multiple use cases and is aimed at providing future-proof bundles. tsdx is an all-in-one solution with testing, ... There's a difference in context and goal
